import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from './ThemeProvider';
import { ThemeSwitcher } from './ThemeSwitcher';
import { Sidebar } from './_components';
import './globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Task manager',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#faf5f5] dark:bg-[#0c0b0b]`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ThemeSwitcher />
          <div className='container mx-auto flex gap-x-5 h-full py-4'>
            <Sidebar />
            <main className='w-full'>{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}